# Controller generated by Typus, use it to extend admin functionality.
class Admin::StaticsController < Admin::MasterController


def sort
@static = Static.find(params[:id])
  @static.children.each do | f |
    f.position = params["level-#{@static.ancestors.size}"].index(f.id.to_s)+1
    f.save
  end
render :nothing => true
end
=begin

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   Static:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     Static: create, read, update, destroy, custom_action
  #
  #   editor:
  #     Static: create, read, update, custom_action_for_an_item
  #

  def index
  end

  def custom_action
  end

  def custom_action_for_an_item
  end

=end

end